[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# The magic solution for Next.js App Router on Netlify
# This ensures that deep links work correctly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200