[build]
  command = "npm install --legacy-peer-deps && npm run netlify-build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# The redirects for Next.js App Router shouldn't point to index.html
# Instead let the Next.js plugin handle the routing
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_serverless"
  status = 200