[build]
  command = "npm install --legacy-peer-deps && npm run netlify-build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# This section is crucial for client-side routing with Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Next.js handles its own routing