[build]
  command = "npm install --legacy-peer-deps && npm run netlify-build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle both with and without trailing slashes for these routes
[[redirects]]
  from = "/orders"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/orders/"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/settings"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/settings/"
  to = "/index.html"
  status = 200
  force = true