[build]
  command = "npm install --legacy-peer-deps && npm run netlify-build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Let the Next.js plugin handle all the routing
# No need for explicit redirects