[build]
  command = "npm config set registry https://registry.npmjs.org/ && npm cache clean --force && (npm install --no-package-lock --legacy-peer-deps --prefer-offline --no-audit || npm run fallback-install) && npm run build"
  publish = ".next"
  ignore = "git diff --quiet HEAD^ HEAD ."

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"
  NEXT_USE_NETLIFY_EDGE = "true"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NPM_FLAGS = "--no-audit --no-fund --prefer-offline --legacy-peer-deps"
  npm_config_package_lock_only = "false"
  npm_config_package_lock = "false"
  npm_config_progress = "false"
  npm_config_audit = "false"

# This is the critical part for deep links to work
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200

[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Add specific routes for orders and settings pages (add these before the catch-all)
[[redirects]]
  from = "/orders"
  to = "/orders"
  status = 200
  force = false

[[redirects]]
  from = "/settings"
  to = "/settings"
  status = 200
  force = false

# Make SPA routing work by redirecting all paths to index.html, but with lower priority
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
